# Generated by Django 5.2 on 2025-05-07 08:54

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hiking', 'Hiking'), ('running', 'Running'), ('biking', 'Mountain biking'), ('cycling', 'Cycling'), ('skiing', 'Downhill skiing'), ('cross-country', 'Cross-country skiing'), ('indoor-climbing', 'Indoor Climbing'), ('outdoor-climbing', 'Outdoor Climbing'), ('wind-surfing', 'Wind Surfing'), ('camping', 'Camping')], max_length=104, null=True),
        ),
    ]
